[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "next build"
publish = ".next"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
